# Generated by Django 6.1 on 2026-08-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('father_name', models.CharField(max_length=50, verbose_name='Ata adı')),
                ('student_class', models.CharField(max_length=20, verbose_name='Sinif')),
                ('birth_date', models.DateField(verbose_name='Doğum tarixi')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='Şagird nömrəsi')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='QR Kod')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Valideynin adı')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Valideynin telefonu')),
                ('parent_relation', models.CharField(default='Ana', max_length=50, verbose_name='Qohumluq əlaqəsi')),
                ('is_in_school', models.BooleanField(default=True, verbose_name='İnternatdadırmı?')),
            ],
        ),
    ]
