# Generated by Django 6.1 on 2026-08-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum tarixi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ata adı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valideynin adı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Valideynin telefonu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_relation',
            field=models.CharField(blank=True, default='Ana', max_length=50, null=True, verbose_name='Qohumluq əlaqəsi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR Kod'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sinif'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Şagird nömrəsi'),
        ),
    ]
