# Generated by Django 6.1 on 2026-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_birth_date_alter_student_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son giriş vaxtı'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_in_school',
            field=models.BooleanField(default=False, verbose_name='İnternatdadırmı?'),
        ),
    ]
